# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from registration_window import Ui_RegistrationWindow
from PySide2.QtWidgets import QApplication

class Ui_MainWindow(object):
    def setupUi(self, ClientMessenger):
        ClientMessenger.setObjectName("ClientMessenger")
        ClientMessenger.resize(784, 608)
        ClientMessenger.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(ClientMessenger)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ClientMessenger)
        ClientMessenger.setStyleSheet("QWidget{ background-color: #2d0c03; }")
        self.frame.setStyleSheet("""QFrame{\n
                                     border: 10px solid #98514b;\n
                                     border-radius: 16px;\n
                                     padding: 10px;\n
                                     background-color: #f4f6ec;\n
                                     border-image: url("my_messenger_logo.png");\n
                                 }""")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(10)
        self.frame.setMidLineWidth(15)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.registrationButton = QtWidgets.QPushButton(self.frame)
        self.registrationButton.setMinimumSize(QtCore.QSize(20, 35))
        self.registrationButton.setBaseSize(QtCore.QSize(20, 35))
        font = QtGui.QFont()
        font.setFamily("STIXGeneral")
        font.setPointSize(12)
        self.registrationButton.setFont(font)
        self.registrationButton.setStyleSheet("QPushButton{ \n"
                                              "color: #f4f6ec;\n"
                                              "background-color: #ac0e28;\n"
                                              "border-radius: 10px;\n"
                                              "border: none;\n"
                                              "}\n"
                                              "QPushButton:focus:pressed\n"
                                              "{ \n"
                                              "color:#2d0c03;\n"
                                              "}\n"
                                              "QPushButton:hover\n"
                                              "{ \n"
                                              "background-color: #bc4558; \n"
                                              "}")
        self.registrationButton.setAutoRepeatDelay(300)
        self.registrationButton.setAutoDefault(False)
        self.registrationButton.setObjectName("registrationButton")
        self.horizontalLayout.addWidget(self.registrationButton)
        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setMinimumSize(QtCore.QSize(20, 35))
        self.loginButton.setBaseSize(QtCore.QSize(20, 35))
        font = QtGui.QFont()
        font.setFamily("STIXGeneral")
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("QPushButton{ \n"
                                       "color: #f4f6ec;\n"
                                       "background-color: #ac0e28;\n"
                                       "border-radius: 10px;\n"
                                       "border: none;\n"
                                       "}\n"
                                       "QPushButton:focus:pressed\n"
                                       "{ \n"
                                       "color:#2d0c03;\n"
                                       "}\n"
                                       "QPushButton:hover\n"
                                       "{ \n"
                                       "background-color: #bc4558; \n"
                                       "}")
        self.loginButton.setAutoRepeatDelay(300)
        self.loginButton.setAutoDefault(False)
        self.loginButton.setObjectName("loginButton")

        # buttons logic
        self.loginButton.clicked.connect(self.open_login_window)
        self.registrationButton.clicked.connect(self.open_registration_window)

        self.horizontalLayout.addWidget(self.loginButton)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(ClientMessenger)
        QtCore.QMetaObject.connectSlotsByName(ClientMessenger)

    def open_registration_window(self):
        self.registration_window = QtWidgets.QWidget()
        registration_widget = Ui_RegistrationWindow()
        registration_widget.setupUi(self.registration_window)
        self.registration_window.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.registration_window.adjustSize()
        screen = QApplication.desktop().screenNumber(QApplication.desktop().cursor().pos())
        center_point = QApplication.desktop().screenGeometry(screen).center()
        self.registration_window.move(center_point.x() - self.registration_window.width(),
                                      center_point.y() - self.registration_window.height())
        self.registration_window.show()

    def open_login_window(self):
        self.registration_window = QtWidgets.QWidget()
        registration_widget = Ui_RegistrationWindow()
        registration_widget.setupUi(self.registration_window)
        self.registration_window.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        self.registration_window.adjustSize()
        screen = QApplication.desktop().screenNumber(QApplication.desktop().cursor().pos())
        center_point = QApplication.desktop().screenGeometry(screen).center()
        self.registration_window.move(center_point.x() - self.registration_window.width(),
                                      center_point.y() - self.registration_window.height())
        self.registration_window.show()

    def retranslateUi(self, ClientMessenger):
        _translate = QtCore.QCoreApplication.translate
        ClientMessenger.setWindowTitle(_translate("ClientMessenger", "ClientMessenger"))
        self.registrationButton.setText(_translate("ClientMessenger", "Registration"))
        self.loginButton.setText(_translate("ClientMessenger", "Login"))
